# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 111111
    url: jdbc:mysql://192.168.1.249:3306/qyx?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
